language: node_js
node_js:
  - "node"

install:
  - npm install
script:
  - npm run build


deploy:
  #deploy to libamtrack.github.io/c2JsGenerator
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN # defined at Travis/Settings/Environment Variables
    keep-history: true
    local-dir: ./dist
    on:
      branch: master
